baseURL = 'https://salmancuso.com'
languageCode = 'en-us'
title = 'Sal Mancuso'
AltTitle1 = 'Neurons & Notions: My Mental Playground'
AltTitle2 = 'Idea Incubator: A Cranial Retreat'
theme = 'ananke'

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "publications"
name = "Publications"
url = "/publications/"
weight = 2

[[menu.main]]
identifier = "posts"
name = "Blog Posts"
url = "/posts/"
weight = 3

[[menu.main]]
identifier = "contact"
name = "Find Me"
url = "/contact/"
weight = 3

[params]
  commentoEnable = false
  read_more_copy = "Read more about this entry"


##################################################
# social media network setups
[ananke.social.networks.bluesky]
slug = "bluesky"
label = "Bluesky"
color = "#1185fe"
profile = "https://bsky.app/profile/%s"
icon = "bluesky" # font awesome brand icon name
link = "https://bsky.app/intent/compose"
[ananke.social.networks.bluesky.particles]
text = "permalink"

[ananke.social.networks.email]
slug = "email"
label = "Email"
profile = false
icon = "envelope" # font awesome free icon name
link = "mailto:spm71@mac.com"
[ananke.social.networks.email.particles]
body = "permalink"
subject = "title"

[ananke.social.networks.github]
slug = "github"
label = "GitHub"
color = "#6cc644"
profile = "https://github.com/salmancuso/"
icon = "github" # font awesome brand icon name


[ananke.social.networks.linkedin]
slug = "linkedin"
label = "LinkedIn"
color = "#0077b5"
profile = "http://linkedin.com/in/salmancuso"
icon = "linkedin" # font awesome brand icon name
link = "https://www.linkedin.com/shareArticle"
[ananke.social.networks.linkedin.particles]
url = "permalink"
title = "title"
summary = "description"
source = "permalink"
params = "mini=true"

[ananke.social.networks.stackoverflow]
slug = "stackoverflow"
label = "Stack Overflow"
color = "#f48024"
profile = "https://stackoverflow.com/users/b8con"
icon = "stack-overflow" # font awesome brand icon name

[ananke.social.networks.youtube]
slug = "youtube"
label = "YouTube"
color = "#cd201f"
profile = "https://www.youtube.com/b8con"
icon = "youtube" # font awesome brand icon name
